import ClassificationGiraudSubcategories.Basic
import ClassificationGiraudSubcategories.RightIdeal
import ClassificationGiraudSubcategories.IdealFilter
import ClassificationGiraudSubcategories.LinearTopology
