import Mathlib.Algebra.Ring.Opposite
import Mathlib.RingTheory.Ideal.Basic

universe u

variable {α : Type u}

/-- Regard a right ideal as a left ideal over the opposite ring. -/
abbrev RightIdeal (A : Type u) [Semiring A] := Ideal (Aᵐᵒᵖ)

namespace RightIdeal

variable [Semiring α]

/-- The right ideal generated by a subset of a ring. -/
abbrev span (s : Set α) : RightIdeal α :=
  Ideal.span (Set.image MulOpposite.op s)

end RightIdeal
