import ClassificationGiraudSubcategories.Basic
import Mathlib.Topology.Algebra.FilterBasis

open scoped Pointwise
open scoped Topology

namespace IdealFilter

variable {A : Type u} [Ring A] (F : IdealFilter A)

def addGroupFilterBasis : AddGroupFilterBasis A where
  sets := {(I : Set A) | I ∈ F}
  nonempty := by
    obtain ⟨I, h_I⟩ := F.nonempty
    exact ⟨I, ⟨I, h_I, rfl⟩⟩
  inter_sets := by
    rintro s t ⟨I, h_I, rfl⟩ ⟨J, h_J, rfl⟩
    refine ⟨I ⊓ J, ⟨I ⊓ J, Order.PFilter.inf_mem h_I h_J, rfl⟩, ?_⟩
    intro x h
    exact h
  zero' := by
    rintro s ⟨I, h_I, rfl⟩
    exact zero_mem I
  add' := by
    rintro s ⟨I, h_I, rfl⟩
    refine ⟨I, ⟨I, h_I, rfl⟩, Set.add_subset_iff.mpr ?_⟩
    exact fun x a y a_1 ↦ add_mem a a_1
  neg' := by
    rintro s ⟨I, h_I, rfl⟩
    exact ⟨I, ⟨I, h_I, rfl⟩, by simp⟩
  conj' := by
    rintro x₀ s ⟨I, h_I, rfl⟩
    exact ⟨I, ⟨I, h_I, rfl⟩, by simp⟩

def ringFilterBasis (uni_F : F.IsUniform) : RingFilterBasis A where
  sets := F.addGroupFilterBasis.sets
  nonempty := F.addGroupFilterBasis.nonempty
  inter_sets := F.addGroupFilterBasis.inter_sets
  zero' := F.addGroupFilterBasis.zero'
  add' := F.addGroupFilterBasis.add'
  neg' := F.addGroupFilterBasis.neg'
  conj' := F.addGroupFilterBasis.conj'
  mul' := by
    rintro s ⟨I, h_I, rfl⟩
    exact ⟨I, ⟨I, h_I, rfl⟩, Set.mul_subset_iff.mpr fun _ h₁ _ h₂ => mul_mem h₁ h₂⟩
  mul_left' := by
    rintro x₀ s ⟨I, h_I, rfl⟩
    refine ⟨I, ⟨I, h_I, rfl⟩, ?_⟩
    intro x h_x
    exact Ideal.mul_mem_left I x₀ h_x
  mul_right' := by
    rintro x₀ s ⟨I, h_I, rfl⟩
    refine ⟨I.colon (Ideal.span {x₀}), ?_, ?_⟩
    · exact ⟨I.colon (Ideal.span {x₀}), uni_F.colon_mem h_I x₀, rfl⟩
    · intro x h_x
      exact Submodule.mem_colon.mp h_x x₀ (Ideal.mem_span_singleton_self x₀)

def addGroupTopology : TopologicalSpace A := (addGroupFilterBasis F).topology

theorem isTopologicalAddGroup :
    letI : TopologicalSpace A := F.addGroupTopology
    IsTopologicalAddGroup A :=
  F.addGroupFilterBasis.isTopologicalAddGroup

def ringTopology (uni_F : F.IsUniform) : TopologicalSpace A :=
  (ringFilterBasis F uni_F).topology

theorem isTopologicalRing (uni_F : F.IsUniform) :
    letI : TopologicalSpace A := F.ringTopology uni_F
    IsTopologicalRing A :=
  (F.ringFilterBasis uni_F).isTopologicalRing

/-- In the topology on `A` induced by an ideal filter `F`, every translate `x +ᵥ I` of an ideal
`I ∈ F` is an open neighborhood of `x`.

This is the basic “linear” feature of `addGroupTopology`: neighborhoods are generated by
(translates of) ideals coming from the filter. -/
lemma isOpen_leftAddCoset (x : A) {I : Ideal A} (h_I : I ∈ F) :
    letI : TopologicalSpace A := F.addGroupTopology
    IsOpen (x +ᵥ (I : Set A)) := by
  letI : TopologicalSpace A := F.addGroupTopology
  refine (isOpen_iff_mem_nhds).mpr ?_
  rintro y ⟨z, h_z, rfl⟩
  have : x +ᵥ (I : Set A) = (x + z) +ᵥ (I : Set A) := by
    have : z +ᵥ (I : Set A) = (I : Set A) :=
      leftAddCoset_mem_leftAddCoset I.toAddSubgroup h_z
    rw [← leftAddCoset_assoc, this]
  rw [this]
  refine ((F.addGroupFilterBasis).nhds_hasBasis (x + z)).mem_iff.2 ?_
  refine ⟨(I : Set A), ?_, ?_⟩
  · exact ⟨I, h_I, rfl⟩
  · intro y hy; exact hy

lemma mem_nhds_iff (a : A) (s : Set A) :
    letI : TopologicalSpace A := F.addGroupTopology
    s ∈ 𝓝 a ↔ ∃ I ∈ F, a +ᵥ (I : Set A) ⊆ s := by
  constructor
  · intro h_s
    rcases ((F.addGroupFilterBasis).nhds_hasBasis a).mem_iff.1 h_s with ⟨t, ht, hts⟩
    rcases ht with ⟨I, hI, rfl⟩
    exact ⟨I, hI, hts⟩
  · rintro ⟨I, hI, hIs⟩
    refine ((F.addGroupFilterBasis).nhds_hasBasis a).mem_iff.2 ?_
    exact ⟨(I : Set A), ⟨I, hI, rfl⟩, hIs⟩

/-- A set is open in `F.addGroupTopology` iff it contains a basic coset neighborhood around
each of its points. -/
lemma isOpen_iff_exists_leftAddCoset_subset (s : Set A) :
    letI : TopologicalSpace A := F.addGroupTopology
    IsOpen s ↔ ∀ a ∈ s, ∃ I ∈ F, a +ᵥ (I : Set A) ⊆ s := by
  letI : TopologicalSpace A := F.addGroupTopology
  constructor
  · intro h_s a h_a
    rw [← F.mem_nhds_iff a s]
    exact IsOpen.mem_nhds h_s h_a
  · intro h
    refine (isOpen_iff_mem_nhds).2 ?_
    intro a h_a
    exact (F.mem_nhds_iff a s).2 (h a h_a)

end IdealFilter
